### ISSUE TITLE
fails, can't open .DS_Store/.bower.json

### ISSUE THREAD

**Issue by iharsuvorau** [sheerun/bower-away#10]
`bower-away` just fails with:

```
Error: ENOTDIR: not a directory, open '/Users/ihar/workspace/projects/baystore_flask/baystore/frontend/static/bower_components/.DS_Store/.bower.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at _callee$ (/Users/ihar/.config/yarn/global/node_modules/bower-away/cli.js:83:40)
    at tryCatch (/Users/ihar/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/ihar/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/ihar/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/ihar/.config/yarn/global/node_modules/bower-away/cli.js:214:30)
    at _next (/Users/ihar/.config/yarn/global/node_modules/bower-away/cli.js:229:9)
    at /Users/ihar/.config/yarn/global/node_modules/bower-away/cli.js:236:7
    at Promise (<anonymous>)
```

I ran:

```
$ yarn global add bower-away
```

And from the directory with `bower.json`
```
$ bower-away
```

There is a strange filename which `bower-away` tries to open: `.DS_Store/.bower.json`.

**Comment by sheerun** [comment]
Thanks for reporting. As a workaround please try to remove bower_components/.DS_Store

**Comment by AndreKelling** [comment]
same here:
`Error: ENOTDIR: not a directory, open '/www/project/web/themes/projectname/bower_components/.gitkeep/.bower.json'`

but removing .gitkeep is making it working.

**Comment by Instrumedley** [comment]
@sheerun this is not possible. I believe it's a system file generated by Mac OS. As soon as you delete it, it creates again.

I'm having the same issue running bower-away

**Comment by yrral86** [comment]
@Instrumedley 
It is generated by finder.  If you close any finder windows that have that directory open, it won't be recreated.

**Comment by kylesnowschwartz** [comment]
deleting the contents of my `.bowerrc` helped get past this issue
