### ISSUE TITLE
Fails with non-hidden `bower.json` files

### ISSUE THREAD

**Issue by martinffx** [sheerun/bower-away#17]
The package I'm using doesn't have a hidden `.bower.json` file, from what I can tell both formats are used quite commonly (at least at one point in time). 

`bower-away` should support both?

```
$ bower-away
Error: ENOENT: no such file or directory, open '/Users/martinrichards/code/work/angular-app/vendor/angular-bindonce/.bower.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at _callee$ (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/cli.js:99:40)
    at tryCatch (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/cli.js:253:30)
    at _next (/Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/cli.js:268:9)
    at /Users/martinrichards/.nvm/versions/node/v6.11.3/lib/node_modules/bower-away/cli.js:275:7
```

**Comment by sheerun** [comment]
thanks for reporting. as a workaround remove any directories without .bower.json after bower installation

**Comment by martinffx** [comment]
What do you mean? I still need the package without the `.bower.json`? 

Should I move the `bower.json` to `.bower.json` then run?

**Comment by sheerun** [comment]
in this case try rm -rf vendor/angular-bindonce and then bower-away
