### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined with version 1.3.2 of yarn

### ISSUE THREAD

**Issue by Pichardito** [sheerun/bower-away#24]
yarn -v 
1.3.2

bower-away --version
1.1.2

I ran `bower-away` in my project with bower.json file and this is the error I get:

```
TypeError: Cannot read property 'slice' of undefined
    at _callee$ (/Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:103:27)
    at tryCatch (/Users/pichardito/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cpichardo/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:296:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/pichardito/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:253:30)
    at _next (/Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:268:9)
    at /Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:275:7
    at /Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:248:12
    at main (/Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:226:17)
    at Object.<anonymous> (/Users/pichardito/.config/yarn/global/node_modules/bower-away/cli.js:348:1)
```
  Please let me know if there's any other information you need for a better understanding of this bug.

**Comment by Pichardito** [comment]
Am I missing some useful information to add to this post?  Please let me know anyone.

**Comment by CalSeebs** [comment]
Same issue here.  Any movement on this?

**Comment by serhii-samoilenko** [comment]
By looking at the code, I can say it happens because one of your dependencies in `bower_components` dir doesn't contain `_source` section in its `.bower.json` file.
Not sure what to do with this, though.

**Comment by lrcarvalho** [comment]
I got the same error: 

TypeError: Cannot read property 'slice' of undefined
at _callee$ (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:103:27)
at tryCatch (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:62:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:296:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/node_modules/regenerator-runtime/runtime.js:114:21)
at step (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:253:30)
at _next (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:268:9)
at /home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:275:7
at new Promise (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/node_modules/core-js/modules/es6.promise.js:164:7)
at /home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:248:12
at main (/home/rof/.nvm/versions/node/v6.2.2/lib/node_modules/bower-away/cli.js:226:17)

Any updates?
