### ISSUE TITLE
Unable to install it with npm: 404 Not Found: bower2yarn@latest

### ISSUE THREAD

**Issue by nelson6e65** [sheerun/bower-away#4]
```
sudo npm install -g bower2yarn
npm ERR! code E404
npm ERR! 404 Not Found: bower2yarn@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-25T21_23_43_012Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'install', '-g', 'bower2yarn' ]
2 info using npm@5.3.0
3 info using node@v7.10.1
4 verbose npm-session 9b4e0f4636e1b887
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/bower2yarn 15402ms
8 silly fetchPackageMetaData error for bower2yarn@latest 404 Not Found: bower2yarn@latest
9 verbose stack Error: 404 Not Found: bower2yarn@latest
9 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
9 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:672:20)
9 verbose stack     at tryOnImmediate (timers.js:645:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
10 verbose cwd /home/nmartell/sources/www/profiler
11 verbose Linux 4.11.10-200.fc25.x86_64
12 verbose argv "/usr/bin/node" "/bin/npm" "install" "-g" "bower2yarn"
13 verbose node v7.10.1
14 verbose npm  v5.3.0
15 error code E404
16 error 404 Not Found: bower2yarn@latest
17 verbose exit [ 1, true ]

```

**Comment by alundiak** [comment]
I have the same behavior. My env:
NodeJS: v8.2.1
NPM: 5.3.0
Bower: 1.8.0
YARN: 0.27.5
Webpack:  3.4.1
Grunt: grunt-cli v1.2.0
MacOS: ProductName: Mac OS X ProductVersion: 10.12.6 BuildVersion: 16G29


cc/ @sheerun any thoughts?

**Comment by sheerun** [comment]
It's not finished nor published yet
